---
title: "Mod Runs report"
author: "Chris Hoover"
date: "1/31/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache = T)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

library(data.table)
library(tidyverse)
```

```{r get_inputs, echo = TRUE}
# Get observed datasets for comparison --------------
load("data/get/got/CA_SF_data2021-02-02.Rdata")

# Census tracts and agents
SF_cts <- readRDS("data/processed/SF_cts_sf.rds")
sf_pop <- readRDS("data/processed/SF_agents_processed.rds")

sim_files <- list.files("data/outputs/Calibration_Sims")
```

# Observed vs simulated hospitalizations  
```{r hosp}
# Fill in MSE between simulated and observed to determine best fit plot below
  hosps_fit <- numeric(length(sim_files))
  sf_hosp_dt <- as.data.table(sf_hosp)
  
sim_hosps <- rbindlist(lapply(sim_files, function(s){
  sim <- readRDS(paste0("data/outputs/Calibration_Sims/", s))
  
  ref_date <- sim[["input_pars"]]$time_pars$ref_date
  bta_base <- sim[["input_pars"]]$trans_pars$bta_base
  sip_red  <- sim[["input_pars"]]$trans_pars$bta_sip_rd
  
  dt <- sim[["epi_curve"]]
  dt_Ih <- dt[state == "Ih",]
    dt_Ih[,ndays   := 1:nrow(dt_Ih)]
    dt_Ih[,Date    := as.Date(ref_date+ndays)]
    dt_Ih[,sip_red := sip_red]
    dt_Ih[,bta     := bta_base]
    dt_Ih[,bta_sip := paste0(bta, sip_red)]
  
    
# Determine "fit"    
  if(nrow(dt_Ih) < (as.numeric(sim[["input_pars"]]$time_pars$t.end- sim[["input_pars"]]$time_pars$t0) - 10)){  #Don't count sims where infection dies out
    sim_obs_mrg <- data.table::merge.data.table(dt_Ih, sf_hosp_dt, by = "Date") 
    sim_obs_mrg[, MSE := (N-HOSP_tot)^2]
    
    hosps_fit[which(s == sim_files)] <- sum(sim_obs_mrg[, MSE], na.rm = T)
  } else {
    hosps_fit[which(s == sim_files)] <- NA_real_
  }
  return(dt_Ih)
  
}))

sf_hosp %>% 
  ggplot() +
    geom_col(aes(x = Date, y = HOSP_tot), 
             col = "darkblue", fill = "blue",
             alpha = 0.4) +
    geom_line(data = sim_hosps,
              aes(x = Date, y = N, col = factor(round(bta, 2)), group = bta_sip),
              alpha = 0.8) +
    theme_classic() +
    labs(x = "Date", y = "Hospitalizations",
         title = "Hospitalizations sim compared to observed",
         col = expression(beta))
  
ggsave(filename = "Plots/Init_Calibrate_Hosps.jpg",
       units = "in", height = 5, width = 8)

sf_hosp %>% 
  ggplot() +
    geom_col(aes(x = Date, y = HOSP_tot), 
             col = "darkblue", fill = "blue",
             alpha = 0.4) +
    geom_line(data = sim_hosps %>% filter(bta == 0.2),
              aes(x = Date, y = N, col = factor(sip_red), group = bta_sip),
              alpha = 0.8) +
    theme_classic() +
    labs(x = "Date", y = "Hospitalizations",
         title = expression(paste0("Hospitalizations sim compared to observed ", beta, "=0.2")),
         col = expression(beta))
  
ggsave(filename = "Plots/Init_Calibrate_Hosps_beta02.jpg",
       units = "in", height = 5, width = 8)

sf_hosp %>% 
  ggplot() +
    geom_col(aes(x = Date, y = HOSP_tot), 
             col = "darkblue", fill = "blue",
             alpha = 0.4) +
    geom_line(data = sim_hosps %>% filter(bta == 0.1),
              aes(x = Date, y = N, col = factor(sip_red), group = bta_sip),
              alpha = 0.8) +
    theme_classic() +
    labs(x = "Date", y = "Hospitalizations",
         title = expression(paste0("Hospitalizations sim compared to observed ", beta, "=0.1")),
         col = expression(beta))
  
ggsave(filename = "Plots/Init_Calibrate_Hosps_beta01.jpg",
       units = "in", height = 5, width = 8)
```

## Best "fit" hosp  
```{r hosp_best}
best_file <- sim_files[which.min(hosps_fit)]

  best_sim <- readRDS(paste0("data/outputs/Calibration_Sims/", best_file))
  
  ref_date <- best_sim[["input_pars"]]$time_pars$ref_date
  bta_base <- best_sim[["input_pars"]]$trans_pars$bta_base
  sip_red  <- best_sim[["input_pars"]]$trans_pars$bta_sip_rd
  
  dt_best <- best_sim[["epi_curve"]]
  dt_best_Ih <- dt_best[state == "Ih",]
    dt_best_Ih[,ndays   := 1:nrow(dt_best_Ih)]
    dt_best_Ih[,Date    := as.Date(ref_date+ndays)]
    dt_best_Ih[,sip_red := sip_red]
    dt_best_Ih[,bta     := bta_base]
    dt_best_Ih[,bta_sip := paste0(bta, sip_red)]
  
sf_hosp %>% 
  ggplot() +
    geom_col(aes(x = Date, y = HOSP_tot), 
             col = "darkblue", fill = "blue",
             alpha = 0.4) +
    geom_line(data = dt_best_Ih,
              aes(x = Date, y = N), 
              col = "red",
              size = 1.2) +
    theme_classic() +
    labs(x = "Date", y = "Hospitalizations",
         title = "Hospitalizations best sim compared to observed")
  
ggsave(filename = "Plots/Init_Calibrate_Best_Hosps.jpg",
       units = "in", height = 5, width = 8)

saveRDS(best_sim, "data/outputs/Calibrate_Best_Hosp.rds")
```


# Observed vs simulated detected cases  
```{r cases}
# Base plot add as we go as building one data.table hits memory limits

jpeg("Plots/Init_Calibrate_ConfCases.jpg")
par(mar = c(3,2,2,1))

plot(sf_test$Date, sf_test$pos, type = "h", col = "grey50",
     xlab = "Date", ylab = "Confirmed Cases")

for(s in sim_files){
  sim <- readRDS(paste0("data/outputs/Calibration_Sims/", s))
  
  bta_base <- sim[["input_pars"]]$trans_pars$bta_base
  sip_red  <- sim[["input_pars"]]$trans_pars$bta_sip_rd
  
  dt <- sim[["linelist_tests"]]
    dt[,sip_red := sip_red]
    dt[,bta     := bta_base]
    dt[,bta_sip := paste0(bta, sip_red)]
  
    dt_sum <- dt[, 
                 .(n_tests = .N, n_pos = sum(test_pos)),
                 by = Date]
    
    lines(dt_sum$Date, dt_sum$n_pos, col = bta_base/0.1)

}

dev.off()

```

```{r cases_gg, eval = FALSE}
tests_sum_by_date <- 
  sim_cases %>% 
  group_by(bta_sip, Date, bta) %>% 
  summarise(n_tests = n(),
            n_pos = sum(test_pos),
            n_Ih = sum(state == "Ih"),
            n_Im = sum(state %in% c("Im", "Imh")),
            n_Ipa = sum(state %in% c("Ip", "Ia")),
            per_pos = n_pos/n_tests)


# Sums of testing data
tests_sum_by_date %>% 
  ggplot() +
  geom_col(data = sf_test,
           aes(x = Date, y = pos),
           fill = "grey50", alpha = 0.5) +
  geom_line(aes(x = as.Date(Date), y = n_pos, col = factor(round(bta, 2)), group = bta_sip)) +
  theme_classic() +
  labs(y = "Positive Tests",
       title = "Confirmed cases compared to observed")

ggsave(filename = "Plots/Init_Calibrate_ConfCases.jpg",
       units = "in", height = 5, width = 8)

tests_sum_by_date %>% 
  ggplot() +
  geom_col(data = sf_test,
           aes(x = Date, y = pct),
           fill = "grey50", alpha = 0.5) +
  geom_line(aes(x = as.Date(Date), y = per_pos, col = factor(round(bta, 2)), group = bta_sip)) +
  theme_classic() +
  labs(title = "Percent positive compared to observed")

ggsave(filename = "Plots/Init_Calibrate_PerPos.jpg",
       units = "in", height = 5, width = 8)

```

# Cases by Census tract-month  
```{r case_ct_mnth, eval = FALSE}
# Get observed case rates by ct by month
  sf_ct_month <- sf_geo %>% 
    mutate(
      month = lubridate::month(Date),
      year = lubridate::year(Date),
      month_year = paste0(month, "_", year)
    ) %>% 
    group_by(month_year, id) %>% 
    summarise(pop              = as.numeric(first(acs_population)),
              new_confirmed    = sum(as.numeric(new_confirmed_cases)),
              month_rate       = new_confirmed/pop,
              month_rate_p100k = month_rate*1e5)

# Same for simulated cases by ct by month
  sim_cases[,month := lubridate::month(Date)]
  sim_cases[,year := lubridate::year(Date)]
  sim_cases[,month_year := paste0(month, "_", year)]

  sims_ct_month <- sim_cases[, 
                             .(n_tests = .N, n_pos = sum(test_pos)),
                             by = c(bta_sip, Date, bta, ct)]
  
  sims_ct_month[, per_pos = n_pos/n_tests]
  
    group_by(bta_sip, Date, bta) %>% 
  
  
  sim_ct_month <- 
sim_tests_by_race <- sim_cases
test_sim <- readRDS("data/outputs/Test_Run_bta0.25_2021-01-29.rds")
test_cases <- test_sim[["linelist_tests"]]





ggsave(filename = "Plots/Init_Calibrate_PerPos.jpg",
       units = "in", height = 5, width = 8)

```

# Cases by race/ethnicity  
*IN DEV*