---
title: "Mod Runs report"
author: "Chris Hoover"
date: "1/31/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

devtools::load_all()

```

```{r get_inputs}
# Get observed datasets for comparison --------------
load("data/get/got/CA_SF_data2021-02-01.Rdata")

# Census tracts and agents
SF_cts <- readRDS("data/processed/SF_cts_sf.rds")
sf_pop <- readRDS("data/processed/SF_agents_processed.rds")

# Get pars
input_pars <- readRDS(("data/processed/input_pars_Dec_start.rds"))

  unpack_list(input_pars)
  
# Get sims files-----------------
vax65p  <- readRDS("data/outputs/ABMv4_Dec_Start__bta0.25_vaxvax65pS_2021-02-01.rds")
vaxessS <- readRDS("data/outputs/ABMv4_Dec_Start__bta0.25_vaxvaxessS_2021-02-01.rds")
vaxessA <- readRDS("data/outputs/ABMv4_Dec_Start__bta0.25_vaxvaxessA_2021-02-01.rds")
  nsims <- length(vax65p)
  
```

# Observed vs simulated hospitalizations  
```{r hosp}
vax65p_hosps <- rbindlist(lapply(1:nsims, FUN = function(s){
  df <- as.data.frame(vax65p[[s]][["epi_curve"]]) %>% 
    filter(state == "Ih") %>% 
    mutate(ndays = row_number(),
           Date = as.Date(ref_date+ndays),
           iter = s,
           vax = "65pS")
  
  return(df)
  
}))

vaxessS_hosps <- rbindlist(lapply(1:nsims, FUN = function(s){
  df <- as.data.frame(vaxessS[[s]][["epi_curve"]]) %>% 
    filter(state == "Ih") %>% 
    mutate(ndays = row_number(),
           Date = as.Date(ref_date+ndays),
           iter = s,
           vax = "essS")
  
  return(df)
  
}))

vaxessA_hosps <- rbindlist(lapply(1:nsims, FUN = function(s){
  df <- as.data.frame(vaxessA[[s]][["epi_curve"]]) %>% 
    filter(state == "Ih") %>% 
    mutate(ndays = row_number(),
           Date = as.Date(ref_date+ndays),
           iter = s,
           vax = "essA")
  
  return(df)
  
}))

vax_hosps <- bind_rows(vax65p_hosps,vaxessS_hosps,vaxessA_hosps)

sf_hosp %>% 
  filter(Date > ref_date) %>% 
  ggplot() +
    geom_col(aes(x = Date, y = HOSP_tot), 
             col = "darkblue", fill = "blue",
             alpha = 0.4) +
    geom_line(data = vax_hosps,
              aes(x = Date, y = N, col = vax, group = iter),
              alpha = 0.7) +
    theme_classic() +
    labs(x = "Date", y = "Hospitalizations",
         title = "Hospitalizations across different vaccination strategies",
         col = "Phase 2\n Vax Strategy")
  
```

# Observed vs simulated detected cases  
```{r cases}
vax65p_cases <- rbindlist(lapply(1:nsims, FUN = function(s){
  dt <- vax65p[[s]][["linelist_tests"]]
    dt[, iter := s]
    dt[, vax := "65pS"]
  
  return(dt)
  
}))

vaxessS_cases <- rbindlist(lapply(1:nsims, FUN = function(s){
  dt <- vaxessS[[s]][["linelist_tests"]]
    dt[, iter := s]
    dt[, vax := "essS"]
  
  return(dt)
  
  return(df)
  
}))

vaxessA_cases <- rbindlist(lapply(1:nsims, FUN = function(s){
  dt <- vaxessA[[s]][["linelist_tests"]]
    dt[, iter := s]
    dt[, vax := "essA"]
  
  return(dt)
  
  return(df)
  
}))

vax_cases <- bind_rows(vax65p_cases,vaxessS_cases,vaxessA_cases)

tests_sum_by_date <- 
  vax_cases %>% 
  group_by(iter, Date, vax) %>% 
  summarise(n_tests = n(),
            n_pos = sum(test_pos),
            n_Ih = sum(state == "Ih"),
            n_Im = sum(state %in% c("Im", "Imh")),
            n_Ipa = sum(state %in% c("Ip", "Ia")),
            per_pos = n_pos/n_tests)


# Sums of testing data
tests_sum_by_date %>% 
  ggplot() +
  geom_col(data = sf_test,
           aes(x = Date, y = pos),
           fill = "grey50", alpha = 0.5) +
  geom_line(aes(x = as.Date(Date), y = n_pos, col = factor(vax), group = iter)) +
  theme_classic() +
  labs(y = "Positive Tests",
       title = "Confirmed cases compared to observed",
       col = "Phase 2\n Vax Strategy")

tests_sum_by_date %>% 
  ggplot() +
  geom_col(data = sf_test,
           aes(x = Date, y = pct),
           fill = "grey50", alpha = 0.5) +
  geom_line(aes(x = as.Date(Date), y = per_pos, col = factor(vax), group = iter)) +
  theme_classic() +
  labs(title = "Percent positive compared to observed",
       col = "Phase 2\n Vax Strategy")
```


