// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// GetCTVisit_cpp
NumericVector GetCTVisit_cpp(NumericVector agents, NumericVector s, NumericMatrix cdfs);
RcppExport SEXP _LEMMAABMv4_GetCTVisit_cpp(SEXP agentsSEXP, SEXP sSEXP, SEXP cdfsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type agents(agentsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type s(sSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type cdfs(cdfsSEXP);
    rcpp_result_gen = Rcpp::wrap(GetCTVisit_cpp(agents, s, cdfs));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_LEMMAABMv4_GetCTVisit_cpp", (DL_FUNC) &_LEMMAABMv4_GetCTVisit_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_LEMMAABMv4(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
