# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title GetCTVisit_cpp
#' @return Vector of CT indices visitied by agents
#' @export
GetCTVisit_cpp <- function(agents, s, cdfs) {
    .Call(`_LEMMAABMv4_GetCTVisit_cpp`, agents, s, cdfs)
}

#' @title test_probs_fx
#' @return Vector of test probabilities for all agents to weight sampling to determine who is tested
#' @export
test_probs_fx <- function(income, income_mult, hpi, essential, essential_prob, t_symptoms, state, t_since_contact, res_inf, adapt_site, adapt_site_mult, tests_avail, case_find_mult, symp_mult, hpi_mult, cont_mult, res_mult, nosymp_state_mult, symp_state_mult, hosp_mult) {
    .Call(`_LEMMAABMv4_test_probs_fx`, income, income_mult, hpi, essential, essential_prob, t_symptoms, state, t_since_contact, res_inf, adapt_site, adapt_site_mult, tests_avail, case_find_mult, symp_mult, hpi_mult, cont_mult, res_mult, nosymp_state_mult, symp_state_mult, hosp_mult)
}

