# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title GetCTVisit_cpp
#' @return Vector of CT indices visitied by agents
#' @export
GetCTVisit_cpp <- function(agents, s, cdfs) {
    .Call(`_LEMMAABMv4_GetCTVisit_cpp`, agents, s, cdfs)
}

